# docker-compose.yml

version: '3.9'

services:
    app:
        build: .
        # image: amanr28/chatengine_server
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        environment:
            - UPLOAD_PATH=/uploads
        env_file:
            - .env
        volumes:
            - uploads:/uploads
        networks:
            - default
    nginx:
        image: nginx:stable
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - uploads:/uploads
        depends_on:
            - app
        networks:
            - default

networks:
    default:
        driver: bridge

volumes:
    mongo_data:

    uploads:
